import type { Question } from "./questions-free";

export const premiumQuestions: Question[] = [
  { kanji: "長野", correct: "ながの", choices: ["ちょうの", "ながの", "なかの", "ながや"], level: "地名" },
  { kanji: "宮城", correct: "みやぎ", choices: ["みやき", "みやぎ", "きゅうじょう", "みやじょう"], level: "地名" },
  { kanji: "熊本", correct: "くまもと", choices: ["くまもと", "ゆうほん", "くまほん", "ゆまもと"], level: "地名" },
  { kanji: "徳島", correct: "とくしま", choices: ["とくしま", "とくじま", "どくしま", "どくじま"], level: "地名" },
  { kanji: "佐賀", correct: "さが", choices: ["さが", "さか", "ざが", "ざか"], level: "地名" },
  { kanji: "秋田", correct: "あきた", choices: ["あきた", "しゅうでん", "あきだ", "しゅうた"], level: "地名" },
  { kanji: "岩手", correct: "いわて", choices: ["がんしゅ", "いわで", "いわて", "がんて"], level: "地名" },
  { kanji: "宮崎", correct: "みやざき", choices: ["みやざき", "きゅうさき", "みやさき", "みやかざき"], level: "地名" },
  { kanji: "大分", correct: "おおいた", choices: ["だいぶ", "おおいた", "おおぶ", "だいた"], level: "地名" },
  { kanji: "石川", correct: "いしかわ", choices: ["せきかわ", "いしがわ", "いしかわ", "せきがわ"], level: "地名" },
  { kanji: "土産", correct: "みやげ", choices: ["どさん", "みやげ", "つちさん", "おみあげ"], level: "N4", hint: "旅行で買う品" },
  { kanji: "今日", correct: "きょう", choices: ["こんにち", "きょう", "いまひ", "こんじつ"], level: "N5" },
  { kanji: "昨日", correct: "きのう", choices: ["さくじつ", "きのう", "きのひ", "ゆうべ"], level: "N5" },
  { kanji: "明日", correct: "あした", choices: ["みょうにち", "あした", "あす", "めいじつ"], level: "N5" },
  { kanji: "一昨日", correct: "おととい", choices: ["いっさくじつ", "おととい", "おとつい", "いちさくじつ"], level: "N4" },
  { kanji: "雰囲気", correct: "ふんいき", choices: ["ふんいき", "ふいんき", "ふんかき", "ふいかき"], level: "N3", hint: "場の空気感" },
  { kanji: "景色", correct: "けしき", choices: ["けいしき", "けしき", "かげいろ", "かげしょく"], level: "N4" },
  { kanji: "眼鏡", correct: "めがね", choices: ["がんきょう", "めがね", "めかね", "まなこ"], level: "N4" },
  { kanji: "足袋", correct: "たび", choices: ["あしぶくろ", "そくたい", "たび", "あしたい"], level: "N3", hint: "和装の靴下" },
  { kanji: "草履", correct: "ぞうり", choices: ["くさばき", "ぞうり", "くつ", "わらじ"], level: "N3", hint: "和装の履物" },
  { kanji: "浴衣", correct: "ゆかた", choices: ["よくい", "ゆかた", "よくや", "ゆか"], level: "N4", hint: "夏の着物" },
  { kanji: "玄関", correct: "げんかん", choices: ["くろまど", "げんかん", "くろかん", "げんまど"], level: "N4" },
  { kanji: "廊下", correct: "ろうか", choices: ["ろうか", "かいろ", "りょうか", "かろう"], level: "N4" },
  { kanji: "押入", correct: "おしいれ", choices: ["おしいれ", "おうにゅう", "おしにゅう", "おういれ"], level: "N4" },
  { kanji: "田舎", correct: "いなか", choices: ["たがや", "いなか", "でんしゃ", "いなか"], level: "N4" },
  { kanji: "木綿", correct: "もめん", choices: ["もくめん", "もめん", "きわた", "もくわた"], level: "N3", hint: "繊維素材" },
  { kanji: "紅葉", correct: "もみじ", choices: ["こうよう", "もみじ", "くれはば", "べにいろ"], level: "N3", hint: "秋の風物詩" },
  { kanji: "梅雨", correct: "つゆ", choices: ["うめあめ", "つゆ", "ばいう", "うめゆ"], level: "N3", hint: "6月の雨季" },
  { kanji: "師走", correct: "しわす", choices: ["しはしり", "しわす", "ほとけはしり", "せんせいはしり"], level: "N3", hint: "12月の別名" },
  { kanji: "弥生", correct: "やよい", choices: ["みせい", "やよい", "やいよ", "みよい"], level: "N3", hint: "3月の別名" },
  // ─── N2/N1 難読漢字 ─────────────────────────────────────────────────────────
  { kanji: "鰐", correct: "わに", choices: ["たに", "わに", "かに", "さに"], level: "N2", hint: "大きな爬虫類" },
  { kanji: "鶯", correct: "うぐいす", choices: ["うぐいす", "かわせみ", "つばめ", "ひばり"], level: "N2", hint: "春を告げる鳥" },
  { kanji: "蝶", correct: "ちょう", choices: ["てふ", "ちょう", "かまきり", "とんぼ"], level: "N2", hint: "花に集まる虫" },
  { kanji: "蛙", correct: "かえる", choices: ["かえる", "いもり", "やもり", "とかげ"], level: "N2", hint: "ぴょんと跳ぶ両生類" },
  { kanji: "鯉", correct: "こい", choices: ["ふな", "こい", "たい", "はも"], level: "N2", hint: "池に泳ぐ観賞魚" },
  { kanji: "蛸", correct: "たこ", choices: ["いか", "たこ", "えび", "かに"], level: "N2", hint: "8本足の海の生物" },
  { kanji: "海苔", correct: "のり", choices: ["うみも", "のり", "かいそう", "わかめ"], level: "N2", hint: "おにぎりに巻く" },
  { kanji: "胡瓜", correct: "きゅうり", choices: ["ごうり", "きゅうり", "なすび", "かぼちゃ"], level: "N2", hint: "緑色の野菜" },
  { kanji: "南瓜", correct: "かぼちゃ", choices: ["なんかぼ", "かぼちゃ", "みなみか", "にんじん"], level: "N2", hint: "ハロウィンの野菜" },
  { kanji: "牛蒡", correct: "ごぼう", choices: ["うしぼ", "ごぼう", "れんこん", "やまいも"], level: "N2", hint: "根菜の一種" },
  { kanji: "独楽", correct: "こま", choices: ["どくら", "こま", "おはじき", "けん玉"], level: "N2", hint: "回して遊ぶ伝統玩具" },
  { kanji: "羽子板", correct: "はごいた", choices: ["はごいた", "なわとび", "こまいた", "はねいた"], level: "N2", hint: "正月の羽根つき道具" },
  { kanji: "凧", correct: "たこ", choices: ["いか", "たこ", "かぜ", "つの"], level: "N2", hint: "正月に空に上げる" },
  { kanji: "御手洗", correct: "みたらし", choices: ["おてあらい", "みたらし", "ごてすすぎ", "みまもり"], level: "N2", hint: "神社で手を清める場所" },
  { kanji: "七五三", correct: "しちごさん", choices: ["ひちいつみ", "しちごさん", "なないつみ", "ひちごみ"], level: "N2", hint: "11月の子供の行事" },
  { kanji: "砂利", correct: "じゃり", choices: ["すなり", "じゃり", "さんり", "つちり"], level: "N2", hint: "小石が混じった砂" },
  { kanji: "吹雪", correct: "ふぶき", choices: ["すいゆき", "ふぶき", "ふゆき", "すいぶき"], level: "N2", hint: "猛烈な雪嵐" },
  { kanji: "雷", correct: "かみなり", choices: ["らい", "かみなり", "いなずま", "つじかぜ"], level: "N2", hint: "雷鳴と稲妻" },
  { kanji: "霞", correct: "かすみ", choices: ["きり", "かすみ", "もや", "しもやけ"], level: "N2", hint: "春の朝の靄" },
  // ─── N1 超難読 ───────────────────────────────────────────────────────────────
  { kanji: "鰹", correct: "かつお", choices: ["まぐろ", "かつお", "かれい", "さわら"], level: "N1", hint: "出汁の代表的な魚" },
  { kanji: "鱈", correct: "たら", choices: ["さば", "たら", "ぶり", "さけ"], level: "N1", hint: "鍋料理に欠かせない魚" },
  { kanji: "鮎", correct: "あゆ", choices: ["いわな", "あゆ", "やまめ", "うぐい"], level: "N1", hint: "清流の女王と呼ばれる魚" },
  { kanji: "鯵", correct: "あじ", choices: ["いわし", "あじ", "さばく", "にしん"], level: "N1", hint: "塩焼きに美味しい青魚" },
  { kanji: "鰤", correct: "ぶり", choices: ["さわら", "ぶり", "かんぱち", "ひらまさ"], level: "N1", hint: "出世魚の代表格" },
  { kanji: "鰺", correct: "あじ", choices: ["いわし", "あじ", "あゆ", "ます"], level: "N1", hint: "アジフライに使う魚" },
  { kanji: "柊", correct: "ひいらぎ", choices: ["つばき", "ひいらぎ", "もみ", "とげき"], level: "N1", hint: "節分に使われる植物" },
  { kanji: "楓", correct: "かえで", choices: ["もみじ", "かえで", "いちょう", "さくら"], level: "N1", hint: "秋に美しく紅葉する木" },
  { kanji: "橘", correct: "たちばな", choices: ["みかん", "たちばな", "ゆず", "だいだい"], level: "N1", hint: "古代の柑橘類" },
  { kanji: "欅", correct: "けやき", choices: ["くぬぎ", "けやき", "ぶな", "なら"], level: "N1", hint: "並木道に多い大木" },
  { kanji: "椿", correct: "つばき", choices: ["さざんか", "つばき", "もくれん", "はくもくれん"], level: "N1", hint: "冬に咲く花木" },
  { kanji: "蓬", correct: "よもぎ", choices: ["ふき", "よもぎ", "せり", "なずな"], level: "N1", hint: "草餅に使う植物" },
  { kanji: "菖蒲", correct: "あやめ", choices: ["いちりん", "あやめ", "ゆり", "きく"], level: "N1", hint: "端午の節句に飾る植物" },
  { kanji: "水仙", correct: "すいせん", choices: ["みずかんむり", "すいせん", "かんしゃ", "みずき"], level: "N1", hint: "春に白い花を咲かせる球根植物" },
  { kanji: "百舌", correct: "もず", choices: ["ひゃくした", "もず", "ひたき", "さんしょうくい"], level: "N1", hint: "鳥の名前、はやにえで有名" },
  { kanji: "鵙", correct: "もず", choices: ["たか", "もず", "くいな", "よたか"], level: "N1", hint: "猛禽類に似た小鳥" },
  { kanji: "翡翠", correct: "かわせみ", choices: ["かわせみ", "ひすい", "みずとり", "かわとり"], level: "N1", hint: "川の宝石と呼ばれる鳥" },
  { kanji: "燕", correct: "つばめ", choices: ["すずめ", "つばめ", "ひばり", "たか"], level: "N1", hint: "春に渡ってくる鳥" },
  { kanji: "鷗", correct: "かもめ", choices: ["たか", "かもめ", "うみねこ", "あほうどり"], level: "N1", hint: "海辺を飛ぶ白い鳥" },
  { kanji: "狐", correct: "きつね", choices: ["たぬき", "きつね", "おおかみ", "むじな"], level: "N1", hint: "稲荷神社の使い" },
  { kanji: "狸", correct: "たぬき", choices: ["きつね", "たぬき", "むじな", "いたち"], level: "N1", hint: "化けるとされる動物" },
  { kanji: "鼬", correct: "いたち", choices: ["おこじょ", "いたち", "テン", "かわうそ"], level: "N1", hint: "細長い胴体の肉食獣" },
  { kanji: "河童", correct: "かっぱ", choices: ["かっぱ", "てんぐ", "おに", "もののけ"], level: "N1", hint: "水辺に棲む伝説の妖怪" },
  { kanji: "天狗", correct: "てんぐ", choices: ["てんぐ", "かっぱ", "おに", "たぬき"], level: "N1", hint: "長い鼻の山の妖怪" },
  // ─── 地名（難読） ─────────────────────────────────────────────────────────
  { kanji: "飛騨", correct: "ひだ", choices: ["とびき", "ひだ", "ひた", "とびだ"], level: "地名", hint: "岐阜県の旧国名" },
  { kanji: "能登", correct: "のと", choices: ["のうと", "のと", "のど", "あわ"], level: "地名", hint: "石川県の半島" },
  { kanji: "甲斐", correct: "かい", choices: ["こうい", "かい", "こうがい", "かいい"], level: "地名", hint: "山梨県の旧国名" },
  { kanji: "淡路", correct: "あわじ", choices: ["あわじ", "たんろ", "うすじ", "あわや"], level: "地名", hint: "兵庫県の島" },
  { kanji: "伊豆", correct: "いず", choices: ["いとう", "いず", "いさば", "いき"], level: "地名", hint: "静岡県の半島" },
  { kanji: "丹後", correct: "たんご", choices: ["にしき", "たんご", "たんこう", "あかま"], level: "地名", hint: "京都府北部の旧国名" },
  { kanji: "播磨", correct: "はりま", choices: ["ばんま", "はりま", "はりば", "ばんば"], level: "地名", hint: "兵庫県南部の旧国名" },
  { kanji: "備前", correct: "びぜん", choices: ["びまえ", "びぜん", "びいち", "そなえまえ"], level: "地名", hint: "岡山県東部の旧国名" },
  { kanji: "薩摩", correct: "さつま", choices: ["さいも", "さつま", "さっと", "ちゅうご"], level: "地名", hint: "鹿児島県の旧国名" },
  { kanji: "肥後", correct: "ひご", choices: ["こえご", "ひご", "ひこう", "こえうしろ"], level: "地名", hint: "熊本県の旧国名" },
  // ─── 人名（難読） ─────────────────────────────────────────────────────────
  { kanji: "一郎", correct: "いちろう", choices: ["かずろう", "いちろう", "いちお", "かつお"], level: "人名", hint: "男性の名前" },
  { kanji: "五月", correct: "さつき", choices: ["ごがつ", "さつき", "いつき", "こつき"], level: "人名", hint: "女性の名前" },
  { kanji: "小春", correct: "こはる", choices: ["こはる", "おはる", "こしゅん", "しょうはる"], level: "人名", hint: "女性の名前、秋の暖かい日も指す" },
  { kanji: "大和", correct: "やまと", choices: ["たいわ", "やまと", "おおかず", "だいわ"], level: "人名", hint: "男性の名前・旧国名" },
  { kanji: "凌", correct: "りょう", choices: ["しのぐ", "りょう", "こえる", "こえ"], level: "人名", hint: "男女共用の名前" },
  { kanji: "紬", correct: "つむぎ", choices: ["よう", "つむぎ", "つじ", "じゅう"], level: "人名", hint: "女性の名前・絹織物" },
  { kanji: "奏", correct: "かなで", choices: ["そう", "かなで", "すすむ", "かなた"], level: "人名", hint: "女性の名前・音楽に関連" },
  { kanji: "颯", correct: "そう", choices: ["かざ", "そう", "はや", "かぜ"], level: "人名", hint: "男性の名前・爽やかな風" },
];
