import type { Question } from "./questions-free";

export const premiumQuestions: Question[] = [
  { kanji: "長野", correct: "ながの", choices: ["ちょうの", "ながの", "なかの", "ながや"], level: "地名" },
  { kanji: "宮城", correct: "みやぎ", choices: ["みやき", "みやぎ", "きゅうじょう", "みやじょう"], level: "地名" },
  { kanji: "熊本", correct: "くまもと", choices: ["くまもと", "ゆうほん", "くまほん", "ゆまもと"], level: "地名" },
  { kanji: "徳島", correct: "とくしま", choices: ["とくしま", "とくじま", "どくしま", "どくじま"], level: "地名" },
  { kanji: "佐賀", correct: "さが", choices: ["さが", "さか", "ざが", "ざか"], level: "地名" },
  { kanji: "秋田", correct: "あきた", choices: ["あきた", "しゅうでん", "あきだ", "しゅうた"], level: "地名" },
  { kanji: "岩手", correct: "いわて", choices: ["がんしゅ", "いわで", "いわて", "がんて"], level: "地名" },
  { kanji: "宮崎", correct: "みやざき", choices: ["みやざき", "きゅうさき", "みやさき", "みやかざき"], level: "地名" },
  { kanji: "大分", correct: "おおいた", choices: ["だいぶ", "おおいた", "おおぶ", "だいた"], level: "地名" },
  { kanji: "石川", correct: "いしかわ", choices: ["せきかわ", "いしがわ", "いしかわ", "せきがわ"], level: "地名" },
  { kanji: "土産", correct: "みやげ", choices: ["どさん", "みやげ", "つちさん", "おみあげ"], level: "N4", hint: "旅行で買う品" },
  { kanji: "今日", correct: "きょう", choices: ["こんにち", "きょう", "いまひ", "こんじつ"], level: "N5" },
  { kanji: "昨日", correct: "きのう", choices: ["さくじつ", "きのう", "きのひ", "ゆうべ"], level: "N5" },
  { kanji: "明日", correct: "あした", choices: ["みょうにち", "あした", "あす", "めいじつ"], level: "N5" },
  { kanji: "一昨日", correct: "おととい", choices: ["いっさくじつ", "おととい", "おとつい", "いちさくじつ"], level: "N4" },
  { kanji: "雰囲気", correct: "ふんいき", choices: ["ふんいき", "ふいんき", "ふんかき", "ふいかき"], level: "N3", hint: "場の空気感" },
  { kanji: "景色", correct: "けしき", choices: ["けいしき", "けしき", "かげいろ", "かげしょく"], level: "N4" },
  { kanji: "眼鏡", correct: "めがね", choices: ["がんきょう", "めがね", "めかね", "まなこ"], level: "N4" },
  { kanji: "足袋", correct: "たび", choices: ["あしぶくろ", "そくたい", "たび", "あしたい"], level: "N3", hint: "和装の靴下" },
  { kanji: "草履", correct: "ぞうり", choices: ["くさばき", "ぞうり", "くつ", "わらじ"], level: "N3", hint: "和装の履物" },
  { kanji: "浴衣", correct: "ゆかた", choices: ["よくい", "ゆかた", "よくや", "ゆか"], level: "N4", hint: "夏の着物" },
  { kanji: "玄関", correct: "げんかん", choices: ["くろまど", "げんかん", "くろかん", "げんまど"], level: "N4" },
  { kanji: "廊下", correct: "ろうか", choices: ["ろうか", "かいろ", "りょうか", "かろう"], level: "N4" },
  { kanji: "押入", correct: "おしいれ", choices: ["おしいれ", "おうにゅう", "おしにゅう", "おういれ"], level: "N4" },
  { kanji: "田舎", correct: "いなか", choices: ["たがや", "いなか", "でんしゃ", "いなか"], level: "N4" },
  { kanji: "木綿", correct: "もめん", choices: ["もくめん", "もめん", "きわた", "もくわた"], level: "N3", hint: "繊維素材" },
  { kanji: "紅葉", correct: "もみじ", choices: ["こうよう", "もみじ", "くれはば", "べにいろ"], level: "N3", hint: "秋の風物詩" },
  { kanji: "梅雨", correct: "つゆ", choices: ["うめあめ", "つゆ", "ばいう", "うめゆ"], level: "N3", hint: "6月の雨季" },
  { kanji: "師走", correct: "しわす", choices: ["しはしり", "しわす", "ほとけはしり", "せんせいはしり"], level: "N3", hint: "12月の別名" },
  { kanji: "弥生", correct: "やよい", choices: ["みせい", "やよい", "やいよ", "みよい"], level: "N3", hint: "3月の別名" },
];
